### PR TITLE
Fix not automatically registered subclasses of built-in subclasses of PFObject.

### LINKED ISSUE #975: PFUser subclass fails on 1.14.0
Hi,

After update to 1.14.0 I'm experiencing constant crash when trying to work with subclass of PFUser.

Actually there is no subclass:
[MyUser currentUser] returns PFUser instance

After I rolled back to 1.13.0 everything works as is.

### PR DESCRIPTION
**Pull request by nlutsenko**
Use `NSObject -conformsToProtocol:`, which recursively checks whether a class conforms to protocol or not.

Fixes #975

### CODE REVIEW

**Comment by rphlfc** [comment]
I am having an error at PFObjectSubclassingController.m method _registerSubclassesInBundle line _registerSubclassesInBundle after updating to version 1.14.1. Had to go back to 1.13.0.

**Comment by kevflynn** [comment]
I'm seeing the same thing.

**Comment by kevflynn** [comment]
FYI @rphlfc - this commit, fixed this issue for me:
https://github.com/ParsePlatform/Parse-SDK-iOS-OSX/compare/1.14.1...master
I manually added it.

**Comment by rphlfc** [comment]
@kevflynn Thanks for sharing. I think I am going to stick with the 1.13.0 and wait till they release it. Thanks again.

**Pull request merged**
