### PR TITLE
Update two documentation directives

### PR DESCRIPTION
**Pull request by hhanesand**

### CODE REVIEW

**Comment by nlutsenko** [comment]
Haha, awesome! Thanks for catching this.

**Comment by nlutsenko** [comment]
Hey @hhanesand, we finally have build breaks resolved - any chance you can rebase this pull request so we can merge it in with tests passing?

**Comment by hhanesand** [comment]
Yes I will hopefully have time to do that later today.

**Comment by nlutsenko** [comment]
Looks like Travis got stuck. Will re-trigger the build here.

**Pull request merged**
