### PR TITLE
Fix logic for file download error handling.

### PR DESCRIPTION
**Pull request by nlutsenko**
@ghugues thanks for finding this! Tremendous help!

### CODE REVIEW

**Comment by ghugues** [comment]
Ah ah no problem, the issue surfaced pretty quickly when I launched my app after asking cocoapods to use master !

**Comment by ghugues** [comment]
Well It seems that doing boolean logic on a Saturday is worse than on a Friday ! (you should check that PR again I think ^^)

**Comment by nlutsenko** [comment]
Should be better now, I hope?

**Comment by richardjrossiii** [comment]
Lol. I'm officially revoking your binary operator card, you now are only allowed to use unary operators.

**Pull request merged**
