### PR TITLE
Unpublicize localeIdentifier property on PFInstallation.

### PR DESCRIPTION
**Pull request by nlutsenko**

### CODE REVIEW

**Comment by grantland** [comment]
LGTM

**Comment by hallucinogen** [comment]
LGTM. @lukas1994, any other `localeIdentifier` call that we might missed?

**Comment by nlutsenko** [comment]
@hallucinogen I used a project-wide search - these are the only ones that we have.

**Comment by hallucinogen** [comment]
:+1:

**Comment by lukas1994** [comment]
I'll update the integration tests.

**Pull request merged**
