### PR TITLE
Removed 'mutable containers' functionality.

### LINKED ISSUE #97: Remove `mutable container` functionality.
Mutable containers right now power the ability to mutate NSArray, NSDictionary, PFGeoPoint after setting them on PFObject.
Here is an example:
```objc
NSMutableArray *array = [NSMutableArray array];

PFObject *object = [PFObject objectWithClassName:@"Example"];
object[@"array"] = array;
[object save];
// This will save an object with empty `array` field.

[array addObject:@"test1"];
[object save];
// This will save an object with `array: [ test1 ]` field
```

This issue is for tracking proposal to remove this functionality from our SDKs. Here are just a few reasons:
- Inconsistency with Cocoa(iOS/OSX) conventions, where you always pass an object by copy, specifically where related to closest thing to Parse - Core Data.
- Inconsistency when fetching an object, where it will remove the mutable containers tracking, as the data will be overwritten by new data from the server.
- Slower Local Datastore performance - a lot of time spent on pinning objects to LDS is spent in checkpointing all mutable containers.

cc @grantland, @hallucinogen, @richardjrossiii

### PR DESCRIPTION
**Pull request by nlutsenko**
Closes #97 
Contributes to #32

### CODE REVIEW

**Comment by richardjrossiii** [comment]
Cleanse it with holy water!

**Comment by FreudGit** [comment]
@nlutsenko arghhh.

**Comment by FreudGit** [comment]
@nlutsenko Still postponed?

**Comment by nlutsenko** [comment]
It's somewhat breaking, and we are trying to make people aware of this coming change before we merge it in.

**Comment by FreudGit** [comment]
@nlutsenko Maybe create a beta and make it available.  I understand you are a bit scared, but the fact are that the LDS query response time are also... scaring at this time. :)  GO, you know you can. :)

**Comment by FreudGit** [comment]
@nlutsenko Do you expect this to be release this month? :)

**Comment by nlutsenko** [comment]
@FreudGit, yes! Absolutely! 1.10 is the next major release that should go out pretty soon.

**Comment by FreudGit** [comment]
@nlutsenko Release in october?  :)

**Comment by nlutsenko** [comment]
Either late Oct, or early Nov.

**Comment by nlutsenko** [comment]
image
Merging after Travis passes on this.

**Comment by kevflynn** [comment]
Yes!!

**Comment by FreudGit** [comment]
@nlutsenko Great work.  Please ship :)

**Pull request merged**
