### PR TITLE
[WIP] Issue #110

### PR DESCRIPTION
**Pull request by kashif**
For issue #110

### CODE REVIEW

**Comment by nlutsenko** [comment]
Good start, ping me whenever you are done.
:grinning:

**Comment by nlutsenko** [comment]
@kashif Closing this one out, as it looks it became stale for a long time.
Feel free to reopen or send a new one, since this still would be super useful to have.

**Comment by kashif** [comment]
sure, the problem was that i need to have a developer program in order to turn on the app extension. If i do that then i do not know how it will work when someone else opens the project who does not have a developer program...

**Comment by nlutsenko** [comment]
Do you explicitly need the paid one, or the free will be sufficient? I can test it for you in every case. Let me know how I can help.

**Pull request closed without merging**
